---
- name: install nginx server
  hosts: all
  become: yes
  tasks:
  - name: installing nginx
    apt:
      name: nginx
      state: present
    notify:
      - reload nginx


  handlers:
  - name: reload nginx
    service:
      name: nginx
      state: reloaded
